### ISSUE TITLE
How do I find out whether a ONION URL is working with Python?

### ISSUE THREAD

**Issue by al3xv3gas** [i3visio/deepify#1]
Title kinda says it. How do I find out using Python whether a onion url is actually working or not? I'm not to keen on using a third party library. This is a question and thanks to anyone in advance!

**Comment by i3visio** [comment]
Hi Al3xv3gas. There are several approaches here:

1. If you are running a Linux system with tor installed (e. g.: `sudo apt-get install tor` in Debian-like systems), the only thing you need is to start the tor service `service tor start` and check the existence of it using `torify` in the curl.
```
sudo apt-get install tor
service tor start
# This will not work as the system will be unable to resolve this domain
curl 3g2upl4pq6kufc4m.onion
# But this yes:
torify curl 3g2upl4pq6kufc4m.onion
```
2. If you are using Python, you can also use this library. You will need to have tor installed, up and running. In Windows systems, downloading and starting the Tor Browser Bundle should be enough, but in Linux this would be easy too:
```
sudo apt-get install tor
service tor start
```
Installing deepify with its dependencies:
```
sudo pip install deepify
```
Writing some sample code such as this one:
```
# Check that you have the Tor Browser running and that the options in ~/.config/Deepify folder are correct
from deepify.tor import Tor
url = "http://3g2upl4pq6kufc4m.onion/"
# Creating the wrapper instance
torwrapper = Tor()
data = torwrapper.getResponse(url)
print data
```
Hope this info helps!

**Comment by al3xv3gas** [comment]
This is exactly what I was hoping for! Thank you very much! What are the responses for fail and success? And can I use the code in my library? That would be awesome! And thanks again, this helped 20000 %! @i3visio

**Comment by al3xv3gas** [comment]
And a further note: I am trying to do what you told me to do and Python is chucking one syntax error after the other at me. Just saying. I'm patching ithe code up as I go along. I'll send you the revised code once it works it for me, if you like. @i3visio And I do not mean to be rude but having to patch up all these errors is a just * a little bit * annoying for me. But anyway, glad I can help squash out errors from this library.

**Comment by al3xv3gas** [comment]
And I really do not mean to be rude! :) @i3visio

**Comment by al3xv3gas** [comment]
The error, that is happening very often is the following:

try:
    some stuff
except SomeException, se:
    do some stuff

now it should be like this:


try:
    some stuff
except SomeException as se:
    do some stuff


@i3visio

**Comment by i3visio** [comment]
Just to know it, is this happening in Python 3? I have just tested it on a Linux machine and it does not throw any error in Python 2 (which is the one we currently use) but it crashes in Python 3. Maybe we should need to do some job on making it work for both versions. Don't worry for the comments. This is still a beta version and we hope the library is suitable for you! 

Ah! Yes, of course you can use it in your own code if you respect the GPLv3 license! Releasing the code under a GPL-compatible version which are a lot (see this link for further info http://gplv3.fsf.org/wiki/index.php/Compatible_licenses). We love Free Software after all!
